services:
    SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff: ~
    SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff: ~
